// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZfW028w7bP3A1UdLn__5P8ALgNbJF4VI',
    appId: '1:779861736063:web:a0d3a7b9ec712b103edd4a',
    messagingSenderId: '779861736063',
    projectId: 'chat-dcfb3',
    authDomain: 'chat-dcfb3.firebaseapp.com',
    storageBucket: 'chat-dcfb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxR00X1SuqiQS-zySSj59Ypol2Yj5-2-c',
    appId: '1:779861736063:android:bbb2dc6475d524e13edd4a',
    messagingSenderId: '779861736063',
    projectId: 'chat-dcfb3',
    storageBucket: 'chat-dcfb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO2_nBxirX0LMQPL7jv6Ub98JaiFMZ-pI',
    appId: '1:779861736063:ios:287da57c94969c653edd4a',
    messagingSenderId: '779861736063',
    projectId: 'chat-dcfb3',
    storageBucket: 'chat-dcfb3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO2_nBxirX0LMQPL7jv6Ub98JaiFMZ-pI',
    appId: '1:779861736063:ios:287da57c94969c653edd4a',
    messagingSenderId: '779861736063',
    projectId: 'chat-dcfb3',
    storageBucket: 'chat-dcfb3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
